# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `libdatadog` gem.
# Please instead update this file by running `bin/tapioca gem libdatadog`.


# source://libdatadog//lib/libdatadog/version.rb#3
module Libdatadog
  class << self
    # This should only be used for debugging/logging
    #
    # source://libdatadog//lib/libdatadog.rb#7
    def available_binaries; end

    # source://libdatadog//lib/libdatadog.rb#27
    def current_platform; end

    # source://libdatadog//lib/libdatadog.rb#68
    def ld_library_path; end

    # source://libdatadog//lib/libdatadog.rb#60
    def path_to_crashtracking_receiver_binary; end

    # source://libdatadog//lib/libdatadog.rb#11
    def pkgconfig_folder(pkgconfig_file_name = T.unsafe(nil)); end

    private

    # source://libdatadog//lib/libdatadog.rb#23
    def vendor_directory; end
  end
end

# source://libdatadog//lib/libdatadog/version.rb#7
Libdatadog::GEM_MAJOR_VERSION = T.let(T.unsafe(nil), String)

# source://libdatadog//lib/libdatadog/version.rb#8
Libdatadog::GEM_MINOR_VERSION = T.let(T.unsafe(nil), String)

# remember to include dot prefix, if needed!
#
# source://libdatadog//lib/libdatadog/version.rb#9
Libdatadog::GEM_PRERELEASE_VERSION = T.let(T.unsafe(nil), String)

# Current libdatadog version
#
# source://libdatadog//lib/libdatadog/version.rb#5
Libdatadog::LIB_VERSION = T.let(T.unsafe(nil), String)

# The gem version scheme is lib_version.gem_major.gem_minor[.prerelease].
# This allows a version constraint such as ~> 0.2.0.1.0 in the consumer (dd-trace-rb), in essence pinning libdatadog to
# a specific version like = 0.2.0, but still allow a) introduction of a gem-level breaking change by bumping gem_major
# and b) allow to push automatically picked up bugfixes by bumping gem_minor.
#
# source://libdatadog//lib/libdatadog/version.rb#16
Libdatadog::VERSION = T.let(T.unsafe(nil), String)
