# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `omniauth-auth0` gem.
# Please instead update this file by running `bin/tapioca gem omniauth-auth0`.


# source://omniauth-auth0//lib/omniauth-auth0/version.rb#1
module OmniAuth; end

# source://omniauth-auth0//lib/omniauth-auth0/version.rb#2
module OmniAuth::Auth0; end

# JWT Validator class
#
# source://omniauth-auth0//lib/omniauth/auth0/jwt_validator.rb#11
class OmniAuth::Auth0::JWTValidator
  # Initializer
  #
  # @param options object
  #   options.domain - Application domain.
  #   options.issuer - Application issuer (optional).
  #   options.client_id - Application Client ID.
  #   options.client_secret - Application Client Secret.
  # @return [JWTValidator] a new instance of JWTValidator
  #
  # source://omniauth-auth0//lib/omniauth/auth0/jwt_validator.rb#21
  def initialize(options, authorize_params = T.unsafe(nil)); end

  # Decodes a JWT and verifies it's signature. Only tokens signed with the RS256 or HS256 signatures are supported.
  #
  # @param jwt string - JWT to verify.
  # @return hash - The decoded token, if there were no exceptions.
  # @see https://github.com/jwt/ruby-jwt
  #
  # source://omniauth-auth0//lib/omniauth/auth0/jwt_validator.rb#48
  def decode(jwt); end

  # Returns the value of attribute domain.
  #
  # source://omniauth-auth0//lib/omniauth/auth0/jwt_validator.rb#12
  def domain; end

  # Sets the attribute domain
  #
  # @param value the value to set the attribute domain to.
  #
  # source://omniauth-auth0//lib/omniauth/auth0/jwt_validator.rb#12
  def domain=(_arg0); end

  # Returns the value of attribute issuer.
  #
  # source://omniauth-auth0//lib/omniauth/auth0/jwt_validator.rb#12
  def issuer; end

  # Sets the attribute issuer
  #
  # @param value the value to set the attribute issuer to.
  #
  # source://omniauth-auth0//lib/omniauth/auth0/jwt_validator.rb#12
  def issuer=(_arg0); end

  # Return a specific key from a JWKS object.
  #
  # @param key string - Key to find in the JWKS.
  # @param kid string - Key ID to identify the right JWK.
  # @return nil|string
  #
  # source://omniauth-auth0//lib/omniauth/auth0/jwt_validator.rb#99
  def jwks_key(key, kid); end

  # Get the JWKS from the issuer and return a public key.
  #
  # @param x5c string - X.509 certificate chain from a JWKS.
  # @return key - The X.509 certificate public key.
  #
  # source://omniauth-auth0//lib/omniauth/auth0/jwt_validator.rb#88
  def jwks_public_cert(x5c); end

  # Get the decoded head segment from a JWT.
  #
  # @return hash - The parsed head of the JWT passed, empty hash if not.
  #
  # source://omniauth-auth0//lib/omniauth/auth0/jwt_validator.rb#78
  def token_head(jwt); end

  # Verify a JWT.
  #
  # @param authorize_params hash - Authorization params to verify on the JWT
  # @param jwt string - JWT to verify.
  # @return hash - The verified token payload, if there were no exceptions.
  #
  # source://omniauth-auth0//lib/omniauth/auth0/jwt_validator.rb#60
  def verify(jwt, authorize_params = T.unsafe(nil)); end

  # Verify a token's signature. Only tokens signed with the RS256 or HS256 signatures are supported.
  # Deprecated: Please use `decode` instead
  #
  # @return array - The token's key and signing algorithm
  #
  # source://omniauth-auth0//lib/omniauth/auth0/jwt_validator.rb#35
  def verify_signature(jwt); end

  private

  # Rails Active Support blank method.
  #
  # @param obj object - Object to check for blankness.
  # @return [Boolean] boolean
  #
  # source://omniauth-auth0//lib/omniauth/auth0/jwt_validator.rb#153
  def blank?(obj); end

  # Get the JWT decode options. We disable the claim checks since we perform our claim validation logic
  # Docs: https://github.com/jwt/ruby-jwt
  #
  # @return hash
  #
  # source://omniauth-auth0//lib/omniauth/auth0/jwt_validator.rb#110
  def decode_opts(alg); end

  # source://omniauth-auth0//lib/omniauth/auth0/jwt_validator.rb#123
  def extract_key(head); end

  # Parse JSON with symbolized names.
  #
  # @param json string - JSON to parse.
  # @return hash
  #
  # source://omniauth-auth0//lib/omniauth/auth0/jwt_validator.rb#160
  def json_parse(json); end

  # Get a JWKS from the domain
  #
  # @return void
  #
  # source://omniauth-auth0//lib/omniauth/auth0/jwt_validator.rb#145
  def jwks; end

  # source://omniauth-auth0//lib/omniauth/auth0/jwt_validator.rb#133
  def rs256_decode_key(kid); end

  # Parse a URI into the desired string format
  #
  # @param uri - the URI to parse
  # @return string
  #
  # source://omniauth-auth0//lib/omniauth/auth0/jwt_validator.rb#167
  def uri_string(uri); end

  # source://omniauth-auth0//lib/omniauth/auth0/jwt_validator.rb#207
  def verify_aud(id_token); end

  # source://omniauth-auth0//lib/omniauth/auth0/jwt_validator.rb#256
  def verify_auth_time(id_token, leeway, max_age); end

  # source://omniauth-auth0//lib/omniauth/auth0/jwt_validator.rb#244
  def verify_azp(id_token); end

  # source://omniauth-auth0//lib/omniauth/auth0/jwt_validator.rb#174
  def verify_claims(id_token, authorize_params); end

  # source://omniauth-auth0//lib/omniauth/auth0/jwt_validator.rb#218
  def verify_expiration(id_token, leeway); end

  # source://omniauth-auth0//lib/omniauth/auth0/jwt_validator.rb#227
  def verify_iat(id_token); end

  # source://omniauth-auth0//lib/omniauth/auth0/jwt_validator.rb#191
  def verify_iss(id_token); end

  # source://omniauth-auth0//lib/omniauth/auth0/jwt_validator.rb#233
  def verify_nonce(id_token, nonce); end

  # source://omniauth-auth0//lib/omniauth/auth0/jwt_validator.rb#267
  def verify_org(id_token, organization); end

  # source://omniauth-auth0//lib/omniauth/auth0/jwt_validator.rb#200
  def verify_sub(id_token); end
end

# Module to provide necessary telemetry for API requests.
#
# source://omniauth-auth0//lib/omniauth/auth0/telemetry.rb#6
module OmniAuth::Auth0::Telemetry
  # Return a telemetry hash to be encoded and sent to Auth0.
  #
  # @return hash
  #
  # source://omniauth-auth0//lib/omniauth/auth0/telemetry.rb#10
  def telemetry; end

  # JSON-ify and base64 encode the current telemetry.
  #
  # @return string
  #
  # source://omniauth-auth0//lib/omniauth/auth0/telemetry.rb#23
  def telemetry_encoded; end

  private

  # source://omniauth-auth0//lib/omniauth/auth0/telemetry.rb#29
  def add_rails_version(telemetry); end
end

# source://omniauth-auth0//lib/omniauth/auth0/errors.rb#3
class OmniAuth::Auth0::TokenValidationError < ::StandardError
  # @return [TokenValidationError] a new instance of TokenValidationError
  #
  # source://omniauth-auth0//lib/omniauth/auth0/errors.rb#5
  def initialize(msg); end

  # Returns the value of attribute error_reason.
  #
  # source://omniauth-auth0//lib/omniauth/auth0/errors.rb#4
  def error_reason; end
end

# source://omniauth-auth0//lib/omniauth-auth0/version.rb#3
OmniAuth::Auth0::VERSION = T.let(T.unsafe(nil), String)

# source://omniauth-auth0//lib/omniauth/strategies/auth0.rb#12
module OmniAuth::Strategies; end

# Auth0 OmniAuth strategy
#
# source://omniauth-auth0//lib/omniauth/strategies/auth0.rb#14
class OmniAuth::Strategies::Auth0 < ::OmniAuth::Strategies::OAuth2
  include ::OmniAuth::Auth0::Telemetry

  # Define the parameters used for the /authorize endpoint
  #
  # source://omniauth-auth0//lib/omniauth/strategies/auth0.rb#85
  def authorize_params; end

  # source://omniauth-auth0//lib/omniauth/strategies/auth0.rb#102
  def build_access_token; end

  # source://omniauth-auth0//lib/omniauth/strategies/auth0.rb#124
  def callback_phase; end

  # Setup client URLs used during authentication
  #
  # source://omniauth-auth0//lib/omniauth/strategies/auth0.rb#26
  def client; end

  # Declarative override for the request phase of authentication
  #
  # source://omniauth-auth0//lib/omniauth/strategies/auth0.rb#108
  def request_phase; end

  private

  # Normalize a domain to a URL.
  #
  # source://omniauth-auth0//lib/omniauth/strategies/auth0.rb#166
  def domain_url; end

  # source://omniauth-auth0//lib/omniauth/strategies/auth0.rb#131
  def jwt_validator; end

  # Check if the options include a client_id
  #
  # @return [Boolean]
  #
  # source://omniauth-auth0//lib/omniauth/strategies/auth0.rb#151
  def no_client_id?; end

  # Check if the options include a client_secret
  #
  # @return [Boolean]
  #
  # source://omniauth-auth0//lib/omniauth/strategies/auth0.rb#156
  def no_client_secret?; end

  # Check if the options include a domain
  #
  # @return [Boolean]
  #
  # source://omniauth-auth0//lib/omniauth/strategies/auth0.rb#161
  def no_domain?; end

  # Parse the raw user info.
  #
  # source://omniauth-auth0//lib/omniauth/strategies/auth0.rb#136
  def raw_info; end
end
